
package service.com.imooc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FirstCXFServicePortType", targetNamespace = "http://www.imooc.com.service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FirstCXFServicePortType {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://www.imooc.com.service/")
    @RequestWrapper(localName = "printReceInfo", targetNamespace = "http://www.imooc.com.service/", className = "service.com.imooc.PrintReceInfo")
    @ResponseWrapper(localName = "printReceInfoResponse", targetNamespace = "http://www.imooc.com.service/", className = "service.com.imooc.PrintReceInfoResponse")
    public String printReceInfo(
        @WebParam(name = "name", targetNamespace = "http://www.imooc.com.service/")
        String name);

}
