
package service.com.imooc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FirstCXFService", targetNamespace = "http://www.imooc.com.service/", wsdlLocation = "http://localhost:8085/firstService?wsdl")
public class FirstCXFService
    extends Service
{

    private final static URL FIRSTCXFSERVICE_WSDL_LOCATION;
    private final static WebServiceException FIRSTCXFSERVICE_EXCEPTION;
    private final static QName FIRSTCXFSERVICE_QNAME = new QName("http://www.imooc.com.service/", "FirstCXFService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8085/firstService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FIRSTCXFSERVICE_WSDL_LOCATION = url;
        FIRSTCXFSERVICE_EXCEPTION = e;
    }

    public FirstCXFService() {
        super(__getWsdlLocation(), FIRSTCXFSERVICE_QNAME);
    }

    public FirstCXFService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FIRSTCXFSERVICE_QNAME, features);
    }

    public FirstCXFService(URL wsdlLocation) {
        super(wsdlLocation, FIRSTCXFSERVICE_QNAME);
    }

    public FirstCXFService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FIRSTCXFSERVICE_QNAME, features);
    }

    public FirstCXFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FirstCXFService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FirstCXFServicePortType
     */
    @WebEndpoint(name = "FirstCXFServicePort")
    public FirstCXFServicePortType getFirstCXFServicePort() {
        return super.getPort(new QName("http://www.imooc.com.service/", "FirstCXFServicePort"), FirstCXFServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FirstCXFServicePortType
     */
    @WebEndpoint(name = "FirstCXFServicePort")
    public FirstCXFServicePortType getFirstCXFServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.imooc.com.service/", "FirstCXFServicePort"), FirstCXFServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FIRSTCXFSERVICE_EXCEPTION!= null) {
            throw FIRSTCXFSERVICE_EXCEPTION;
        }
        return FIRSTCXFSERVICE_WSDL_LOCATION;
    }

}
